name: Deno CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write   # needed for deployment to GitHub Pages

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A

  deploy:
    needs: test   # deploy only if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Build step - adjust based on your project setup
      # If you have a deno.json task like `"build": "deno task build"`, use that
      - name: Build project
        run: |
          if [ -f deno.json ]; then
            deno task build
          else
            mkdir dist
            cp -r * dist/
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist   # change if your build output is different
